# Hilos Virtuales para escalabilidad
spring.threads.virtual.enabled=true

# Configuración para Base de Datos
spring.datasource.url=jdbc:sqlite:springbootdemo.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Para ver los SQL Queries en consola
spring.jpa.show-sql=true

# Configuración para Redis
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

